name:                rfid-kodi-control
version:             0.1.0.0
github:              "bneijt/rfid-kodi-control"
license:             GPL-3
author:              "Bram Neijt"
maintainer:          "bram@neijt.nl"
copyright:           "2019 Bram Neijt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/bneijt/rfid-kodi-control#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - evdev
  - containers
  - req
  - bytestring
  - yaml
  - aeson


executables:
  rfid-kodi-control-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -static
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    cc-options: -static
    # ld-options: -static -pthread
    dependencies:
    - rfid-kodi-control
    - yaml
    - containers
    - req
    - aeson
    - bytestring
    - text
    - modern-uri

tests:
  rfid-kodi-control-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rfid-kodi-control
